development:
  adapter: postgresql
  database: elk_sports
  username: elk_sports
  password: elk_sports
  encoding: unicode
  pool: 5

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: elk_sports
  username: elk_sports
  password: elk_sports
  encoding: unicode
  pool: 5

production:
  adapter: postgresql
  database: elk_sports
  username: elk_sports
  password: elk_sports
  encoding: unicode
  pool: 5

cucumber:
  <<: *test
